### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [alexey-kuliw/kottans-homework#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить
```html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```

**Comment by mkozhukharenko** [comment]
wrong use case for [dl](https://html.spec.whatwg.org/multipage/semantics.html#the-dl-element) [dd](https://html.spec.whatwg.org/multipage/semantics.html#the-dd-element) [dt](https://html.spec.whatwg.org/multipage/semantics.html#the-dt-element)

```html
<dl> 
				<dt>Пользователь</dt>
				<dd>@rayproud</dd>
				
				<dt>карма</dt>
				<dd><data value=2>2,0</data></dd>
				
				<dt>рейтинг</dt>
				<dd><data value=0.0>0,0</data></dd>
			</dl>
```

**Comment by mkozhukharenko** [comment]
user name can be a `figcaption `
```html
<figure>
	<img src=userpic.png alt=rusmvb-userpic>
</figure>
<a href=userl-link>rusmvb</a>
```
Its a description to the image, isn't it?

**Comment by mkozhukharenko** [comment]
```html

			<article>
				<header>
					<figure>
						<img src=userpic.png alt=rusmvb-userpic>
					</figure>
					<a href=userl-link>rusmvb</a>
					<time datetime="2014-12-8 12:01">8 декабря 2014 в 12:01</time>
					<ul>
						<li><a href=#>comment</a></li>
						<li><a href=#>branch</a></li>
						<li><a href=#>previous</a></li>
					</ul>
				</header>
				<main>
					<p>Полностью согласен, что сложновато. Это больше вопросы не на умение работать с html, а на знание специфических возможностей, которые в большинстве проектов совсем не уместны. На крайний случай в спецификации эти данные можно найти, а не в голове их таскать.</p>
				</main>
```
it isn't nessesary to put a `main` element into each article. Its also a  matter of dispute. Don misuse this element since spec has dual description about this

**Comment by mkozhukharenko** [comment]
check your markup [here](https://validator.w3.org/nu/) and fix errors, please.

**Comment by mkozhukharenko** [comment]
In general look good, especially an outline 👍

**Comment by shvaikalesh** [comment]
> it isn't nessesary to put a main element into each article. Its also a matter of dispute. Don misuse this element since spec has dual description about this

It is allowed by whatwg spec, but I see no reason to use it more than once.

**Comment by alexey-kuliw** [comment]
I've fixed all comments. Please check again.

**Comment by mkozhukharenko** [comment]
@shvaikalesh can you take a look? concerning this https://github.com/alexey-kuliw/kottans-homework/issues/2#issuecomment-220925508 issue

**Comment by shvaikalesh** [comment]
`d*` were misused, as @mkozhukharenko mentioned
